[package]
name = "lab3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"

[dependencies.rusqlite]
version = "0.32.1"
features = ["bundled"]
